In [1]:
import pandas as pd
import numpy as np

In [4]:
data = {'one': pd.Series([1,2,5], index = ['a','b','e']),
        'two':pd.Series([1,2,3,4], index = ['a','b','c','d'])}
table = pd.DataFrame(data)
print(table)

   one  two
a  1.0  1.0
b  2.0  2.0
c  NaN  3.0
d  NaN  4.0
e  5.0  NaN


In [10]:
from sklearn.impute import SimpleImputer
im = SimpleImputer(missing_values = np.nan, strategy = 'mean')
im.fit(table)
imputed_data = im.transform(table.values)
print(type(imputed_data))
print(pd.DataFrame(imputed_data, columns = ['one', 'two']))

<class 'numpy.ndarray'>
        one  two
0  1.000000  1.0
1  2.000000  2.0
2  2.666667  3.0
3  2.666667  4.0
4  5.000000  2.5


C:\Users\hp\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


In [18]:
data = {'Customer_id': pd.Series([1,2,3,4,5]),
        'Loan_type':   pd.Series(['home_loan','Personal_loan','education_loan', 'home_loan', 'credit_loan']),
        'Income':      pd.Series(['30K', '25K', '15K', '40K', '35K'])}
loan_info = pd.DataFrame(data)
print(loan_info)

   Customer_id       Loan_type Income
0            1       home_loan    30K
1            2   Personal_loan    25K
2            3  education_loan    15K
3            4       home_loan    40K
4            5     credit_loan    35K


In [20]:
# get dummies 
pd.get_dummies (loan_info, prefix_sep = '_', drop_first = True)

Customer_id  Loan_type_credit_loan  Loan_type_education_loan  \
0            1                  False                     False   
1            2                  False                     False   
2            3                  False                      True   
3            4                  False                     False   
4            5                   True                     False   

   Loan_type_home_loan  Income_25K  Income_30K  Income_35K  Income_40K  
0                 True       False        True       False       False  
1                False        True       False       False       False  
2                False       False       False       False       False  
3                 True       False       False       False        True  
4                False       False       False        True       False

In [23]:
# label encoder 
from sklearn.preprocessing import LabelEncoder 
labelencoder = LabelEncoder()
loan_info_upd = loan_info.apply(labelencoder.fit_transform)
print(loan_info_upd)

   Customer_id  Loan_type  Income
0            0          3       2
1            1          0       1
2            2          2       0
3            3          3       4
4            4          1       3


In [24]:
from sklearn.preprocessing import OneHotEncoder
obj = OneHotEncoder()
x = obj.fit_transform(loan_info).toarray()
print(x)

[[1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0.]]
